INSERT IGNORE INTO payers (`payer`)
VALUES
("AETNA - (POS)"),
("COMMUNITY HEALTH PLAN OF WASHINGTON - (PPO)"),
("COORDINATED CARE OF WASHINGTON - (Medicaid)"),
("PREMERA BLUE CROSS - (PPO)"),
("UNITED HEALTHCARE INSURANCE COMPANY - (EPO)"),
("UNITED HEALTHCARE INSURANCE COMPANY - (HMO-MR)"),
("UNITED HEALTHCARE INSURANCE COMPANY - (Indemnity)"),
("UNITED HEALTHCARE INSURANCE COMPANY - (POS)"),
("CIGNA BEHAVIORAL HEALTH INC. - (POS)"),
("Cigna Health and Life Insurance Company - (POS)"),
("Allied ASO - (PPO)"),
("ASURIS NORTHWEST HEALTH - (PPO)"),
("UNITED HEALTHCARE INSURANCE COMPANY - (PPO)"),
("AETNA - (PPO)"),
("GreatWestHealthcare-CIGNA - (POS)"),
("UMR NRECA - (PPO)"),
("AMERIGROUP WASHINGTON, INC. - (Medicaid)"),
("KFHP of WA Options Inc - (HMO)"),
("MOLINA HEALTHCARE OF WASHINGTON, INC - (Medicaid)"),
("ASURIS NORTHWEST HEALTH - (Indemnity)"),
("KFHP of WA - (HMO)"),
("PREMERA BLUE CROSS - (Indemnity)"),
("WMI Mutual Insurance Company - (Indemnity)"),
("Allied Benefit Systems - (Indemnity)"),
("AMBETTER - (HMO)"),
("AMGP GEORGIA MANAGED CARE CO INC - (Medicaid)"),
("Benefit Administrative Systems - (Indemnity)"),
("Benefit Administrative Systems - (PPO)"),
("Benefit Management LLC - (PPO)"),
("CWIBENEFITS, INC - (POS)"),
("Group Administrators, Ltd. - (PPO)"),
("FIRST CHOICE HEALTH - (PPO)"),
("GreatWestHealthcare-CIGNA - (PPO)"),
("HUMANA INC. - (HMO-MR)"),
("UMR - (PPO)"),
("Premera Blue Cross - (PPO)"),
("HealthNow Administrators - (PPO)"),
("Lifewise Health Plan of WA - (PPO)"),
("COORDINATED CARE OF WASHINGTON - (HMO)"),
("KFHPWO, Inc FEP Program - (HMO)"),
("USA Benefits & Administrators - (PPO)"),
("HealthComp Administrators - (PPO)"),
("CIGNA BEHAVIORAL HEALTH, INC. - (HMO)"),
("Lucent Health Solutions - (PPO)"),
("UNITED HEALTHCARE INSURANCE COMPANY - (HMO)"),
("BeneSys, Inc. - (PPO)"),
("CIGNA BEHAVIORAL HEALTH - (HMO)"),
("Allegiance Benefit Plan Management - (PPO)"),
("Summit Administrators, Inc. - (PPO)"),
("Nova Healthcare Administrators - (PPO)"),
("E.D.I.S. - (PPO)"),
("UNITED OF OMAHA LIFE INSURANCE COMPANY - (Indemnity)"),
("Staff Benefit Management and Admin - (PPO)"),
("Beacon Health Options, Inc. - (POS)"),
("Benesys - (PPO)"),
("LIFEWISE OF WASHINGTON - CLAIMS - (PPO)"),
("REGENCE BLUESHIELD - (PPO)"),
("Discounted Cash Charge"),
("Gross Charge"),
("De-identifiedMax"),
("De-identifiedMin");